<a href="https://colab.research.google.com/github/Oreoluwa99/demo_test/blob/main/Ustacky_Microdegree_Practices_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a_list = [1,2,3]

In [4]:
array = np.array(a_list)

In [5]:
array

array([1, 2, 3])

In [6]:
a_list = [(1,2,3), (4,5,6), (7,8,9)]

In [8]:
array2 = np.array(a_list)

In [9]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr = np.zeros(2)

In [15]:
arr

array([0., 0.])

In [16]:
arr2 = np.zeros((2,2))

In [17]:
arr2

array([[0., 0.],
       [0., 0.]])

In [25]:
arr3 = np.random.rand(10,10)

In [26]:
arr3

array([[0.28521324, 0.38312671, 0.84641486, 0.38031724, 0.65051233,
        0.04774402, 0.41516577, 0.96679978, 0.50873261, 0.94292384],
       [0.97872447, 0.07038602, 0.77336549, 0.98008953, 0.21629447,
        0.56603689, 0.79680961, 0.08685101, 0.22412048, 0.63116954],
       [0.70996362, 0.01434015, 0.51715221, 0.43538674, 0.16298547,
        0.32474418, 0.80581889, 0.45654989, 0.63719176, 0.38436347],
       [0.84731775, 0.79432767, 0.15625171, 0.68164991, 0.58395217,
        0.18986048, 0.11458947, 0.55304757, 0.1580032 , 0.82778935],
       [0.05325156, 0.63860876, 0.66315034, 0.04322639, 0.06762105,
        0.96238941, 0.59469629, 0.65295856, 0.14582026, 0.8958818 ],
       [0.39757452, 0.31864123, 0.03493861, 0.46638531, 0.46159496,
        0.97841981, 0.76077314, 0.09885243, 0.69957406, 0.79762364],
       [0.61557256, 0.33856352, 0.6256628 , 0.73388061, 0.9357171 ,
        0.14600436, 0.56432942, 0.78442034, 0.49992517, 0.78191529],
       [0.39916588, 0.10617403, 0.0991675