<a href="https://colab.research.google.com/github/Oreoluwa99/demo_test/blob/main/Ustacky_Microdegree_Practices_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr1 = np.array([2,4])

In [4]:
arr1

array([2, 4])

In [5]:
arr2 = np.array([1,2])

In [6]:
arr2

array([1, 2])

In [7]:
arr1 + arr2

array([3, 6])

In [9]:
arr1 - arr2

array([1, 2])

In [10]:
arr2 - arr1

array([-1, -2])

In [11]:
arr1 * arr2

array([2, 8])

In [12]:
arr1 * 2

array([4, 8])

In [17]:
arr3 = np.array([[1,2], [3,4], [5,6]])

In [19]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
arr3 * 3

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [21]:
arr1 + arr3

array([[ 3,  6],
       [ 5,  8],
       [ 7, 10]])

In [22]:
arr3.max()

6

In [23]:
(arr1+arr3).max()

10

In [24]:
arr3.max(axis=0)

array([5, 6])

In [25]:
arr3.max(axis=1)

array([2, 4, 6])

In [29]:
arr3.dtype

dtype('int64')

In [30]:
#Mean Square Error Approximation with Numpy
import numpy as np


In [32]:
predictions = np.array([2,5,6])
labels = np.array([1,5,8])


In [36]:
MSE = (1/3) * np.sum(np.square(predictions - labels))

In [37]:
MSE

1.6666666666666665