<a href="https://colab.research.google.com/github/Oreoluwa99/demo_test/blob/main/Ustacky_Data_Science_Microdegree_Practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [6]:
ser = pd.Series(['Lagos', 'kaduna', 'Ondo'])

In [7]:
ser

0     Lagos
1    kaduna
2      Ondo
dtype: object

In [9]:
ser = pd.Series([1,2,4,5,6,9])

In [10]:
ser

0    1
1    2
2    4
3    5
4    6
5    9
dtype: int64

In [11]:
state = ['Lagos', 'Ogun', 'Imo']
capitals = ['Ikeja', 'Abeokuta', 'Owerri']

In [13]:
ser = pd.Series(index=state, data=capitals)

In [14]:
ser

Lagos       Ikeja
Ogun     Abeokuta
Imo        Owerri
dtype: object

In [17]:
State_Dict = ({'Lagos':'Ikeja', 
               'Nassarawa':'Lafia',
               'FCT':'Abuja'})

In [18]:
ser = pd.Series(State_Dict)

In [19]:
ser

Lagos        Ikeja
Nassarawa    Lafia
FCT          Abuja
dtype: object

In [20]:
arr = np.arange(1,10)

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
ser = pd.Series(arr)

In [23]:
ser

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [24]:
arr1 = np.random.rand(5)

In [25]:
arr1

array([0.78867072, 0.09284116, 0.94875132, 0.62254257, 0.70860087])

In [26]:
ser = pd.Series(arr1)

In [27]:
ser

0    0.788671
1    0.092841
2    0.948751
3    0.622543
4    0.708601
dtype: float64

In [28]:
arr1

array([0.78867072, 0.09284116, 0.94875132, 0.62254257, 0.70860087])

In [30]:
pd.read_csv('daily-bike-share.csv')

FileNotFoundError: ignored

In [31]:
pd.read_csv('test.csv')

FileNotFoundError: ignored

In [32]:
pd.read_csv('state_and_capital.csv')

FileNotFoundError: ignored

In [33]:
import numpy as np
import pandas as pd

In [34]:
#Creating a list and dictionary
a_list = [40,2,1,5,53,34]
state = ['Lagos', 'Kaduna', 'Gombe']
state_dict = ({'Adamawa':'Yola',
              'Yobe':'Damaturu',
               'Anambra':'Awka'})


In [35]:
ser = pd.Series(state_dict)

In [36]:
ser

Adamawa        Yola
Yobe       Damaturu
Anambra        Awka
dtype: object

In [43]:
ser.index

Index(['Adamawa', 'Yobe', 'Anambra'], dtype='object')

In [41]:
ser.values

array(['Yola', 'Damaturu', 'Awka'], dtype=object)

In [45]:
ser.dtypes

dtype('O')

In [46]:
ser1 = pd.Series(a_list)

In [47]:
ser1

0    40
1     2
2     1
3     5
4    53
5    34
dtype: int64

In [49]:
ser1.mean()

22.5

In [50]:
ser1.sum()

135

In [52]:
ser1.astype(str)

0    40
1     2
2     1
3     5
4    53
5    34
dtype: object

In [53]:
ser1.sum()

135

In [54]:
list(ser1)

[40, 2, 1, 5, 53, 34]

In [55]:
ser

Adamawa        Yola
Yobe       Damaturu
Anambra        Awka
dtype: object

In [56]:
dict(ser)

{'Adamawa': 'Yola', 'Anambra': 'Awka', 'Yobe': 'Damaturu'}

In [57]:
ser1

0    40
1     2
2     1
3     5
4    53
5    34
dtype: int64

In [61]:
sorted(ser1)

[1, 2, 5, 34, 40, 53]

In [62]:
len(ser1)

6

In [63]:
import numpy as np
import pandas as pd


In [64]:
a_list = [40, 2, 1, 53, 34]

In [65]:
ser1 = pd.Series(a_list)

In [66]:
ser1

0    40
1     2
2     1
3    53
4    34
dtype: int64

In [68]:
ser1.min()

1

In [69]:
ser1.max()

53

In [70]:
ser1.idxmax()

3

In [72]:
ser1.idxmin()

2

In [74]:
ser1[ser1.idxmax()]

53

In [75]:
(ser1.sum())/(ser1.count())

26.0

In [76]:
ser1.describe()

count     5.000000
mean     26.000000
std      23.398718
min       1.000000
25%       2.000000
50%      34.000000
75%      40.000000
max      53.000000
dtype: float64

In [77]:
#age_list
age = [40, 17, 18, 35, 25]


In [90]:
#state list
state = ['Lagos', 'Delta', 'Kaduna']

In [104]:
state_dict = {
    'Lagos':'Ikeja',
    'Delta':'Asaba',
    'Kaduna':'Kaduna'}

In [105]:
ser1 = pd.Series(age)
ser2 = pd.Series(state)
ser3 = pd.Series(state_dict)

In [106]:
ser2

0     Lagos
1     Delta
2    Kaduna
dtype: object

In [107]:
ser3

Lagos      Ikeja
Delta      Asaba
Kaduna    Kaduna
dtype: object

In [108]:
ser2.map(ser3)

0     Ikeja
1     Asaba
2    Kaduna
dtype: object

In [109]:
#trying out the anonymous function (i.e. the lambda fuction)

ser1

0    40
1    17
2    18
3    35
4    25
dtype: int64

In [110]:
ser1.map(lambda x: x+1)

0    41
1    18
2    19
3    36
4    26
dtype: int64

In [111]:
def age_classify(age):
  if age < 20:
    return 'Teenagers'
  else:
    return 'Adults'

In [114]:
ser1.apply(age_classify)

0       Adults
1    Teenagers
2    Teenagers
3       Adults
4       Adults
dtype: object

In [115]:
ser1.apply(lambda x: x+1)

0    41
1    18
2    19
3    36
4    26
dtype: int64