<a href="https://colab.research.google.com/github/Oreoluwa99/demo_test/blob/main/Ustacky_Microdegree_Practices_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [8]:
array = np.random.randint(0,100, 16)

In [9]:
array

array([84, 58, 11, 10, 41, 44, 35, 21, 31, 39, 17, 95, 79,  5, 58, 78])

In [13]:
array.shape

(16,)

In [15]:
array.ndim

1

In [17]:
array.reshape(4,4)
#This reshapes the array and returns rows of 4 columns and 4 rows

array([[84, 58, 11, 10],
       [41, 44, 35, 21],
       [31, 39, 17, 95],
       [79,  5, 58, 78]])

In [25]:
array2d = array.reshape(4,4)
#This reshapes the new array

In [26]:
array2d.shape

(4, 4)

In [12]:
array2 = np.random.rand(100,100)

In [11]:
array2

array([[[0.00295329, 0.06756582, 0.17810035, ..., 0.64427727,
         0.18666617, 0.17831584],
        [0.97403831, 0.49400135, 0.38074383, ..., 0.00287076,
         0.8367898 , 0.00698407],
        [0.70951111, 0.37231122, 0.3472935 , ..., 0.22023139,
         0.63080627, 0.14972917],
        ...,
        [0.89022263, 0.66298104, 0.5414093 , ..., 0.8873789 ,
         0.33770405, 0.26069974],
        [0.11175224, 0.28141127, 0.5418432 , ..., 0.27891827,
         0.01931695, 0.80354622],
        [0.71560654, 0.73815798, 0.52127456, ..., 0.33473604,
         0.07409996, 0.64883267]],

       [[0.78659156, 0.18681344, 0.80544476, ..., 0.1610955 ,
         0.84476206, 0.79455572],
        [0.88397102, 0.83103052, 0.52675081, ..., 0.45783153,
         0.3163319 , 0.86064916],
        [0.29165039, 0.45150101, 0.66275883, ..., 0.43160593,
         0.00283027, 0.58852742],
        ...,
        [0.24273215, 0.18681831, 0.03364603, ..., 0.10625461,
         0.76221322, 0.99018463],
        [0.4

In [14]:
array2.shape

(100, 100)